### PR TITLE
[Issue-34] Move CI to GitHub actions

### PR DESCRIPTION
**Pull request by gaol**
Motivation:

Fixes: #34

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by gaol** [comment]
@vietj @pmlopes  this is ready for review

What the PR tries to change are:

- Enable Python client GitHub Actions CI:
   - Removed duplicated `README`
   - Updated `python/setup.py` to use `setuptools`, specify the initial version to be: `1.0.0.dev0`
   - Use `pypa/gh-action-pypi-publish@v1.4.1` to publish the new release to [pypi.org](https://pypi.org/) on new tag and if the version in `python/setup.py` does not contain `dev`.
      - This needs a secret: `PYPI_API_TOKEN` configured to be [the API Token of pypi](https://pypi.org/manage/account/token/) so that it can upload artifacts to pypi.

- Enable NodeJS client GitHub Actions CI:
   - Changed version from `3.4.0` to `1.0.0-SNAPSHOT` in `nodejs/package.json`. I did not find any package named '@vertx/vertx-tcp-eventbus-client' in [NPM](https://www.npmjs.com/), so I think it should be OK to start with `1.0.0` for the release
      - The package may need to be renamed from `vertx3-tcp-eventbus-client` to `@vertx/vertx-tcp-eventbus-client` in a new PR
   - Use `JS-DevTools/npm-publish@v1` to publish new version to [NPM](https://www.npmjs.com/) on new tag and if the version in `nodejs/package.json` does not end with `-SNAPSHOT`.
      - This needs a secret: `NPM_TOKEN` configured to be [the Access Token of NPM](https://www.npmjs.com/settings/vertx/tokens) so that it can upload artifacts to NPM.

- Enable Javascript client GitHub Actions CI:
   - Changed version from `1.0.0-2` to `1.0.0-3-SNAPSHOT` in `javascript/package.json` to start new version development. There is a package named [@vertx/eventbus-bridge-client.js](https://www.npmjs.com/package/@vertx/eventbus-bridge-client.js) in npm already, the next version should be `1.0.0-3` or higher.
   - Use `JS-DevTools/npm-publish@v1` to publish new version to [NPM](https://www.npmjs.com/) on new tag and if the version in `javascript/package.json` does not end with `-SNAPSHOT`.
      - This needs a secret: `NPM_TOKEN` configured to be [the Access Token of NPM](https://www.npmjs.com/settings/vertx/tokens) so that it can upload artifacts to NPM.
         - The `NPM_TOKEN` is the same as the one configured for NodeJS client

- Enable Go client GitHub Actions CI:
   - Updated `Go/build.sh` to be able to run in both local and CI env
   - Set up workflow to run Go build
   - Go library can be shared by github repository, so no needs to publish elsewhere.

- Enable C# client GitHub Actions CI:
   - Updated `C#/build.sh` to use `mcr.microsoft.com/dotnet/sdk:latest` for latest dotnet sdk
   - Updated `C#/vertx-eventbus/vertx-eventbus.csproj` to specify:
      - `PackageID` to be `vertx.eventbus.client`
      - `Version` to be `1.0.0-SNAPSHOT`   # there is no package with the PackageID in NuGet yet.
      - Updated `TargetFramework` from `netcoreapp1.1` to `netcoreapp2.1;netcoreapp3.1;net48` to use latest version.
   - Use `brandedoutcast/publish-nuget@v2` to publish the new release to [nuget.org](https://www.nuget.org/) on new tag and if the version in `C#/vertx-eventbus/vertx-eventbus.csproj` does not end with `-SNAPSHOT`.
      - This needs a secret: `NUGET_API_KEY` configured to be [the API Keys of NuGet](https://www.nuget.org/account/apikeys) so that it can upload artifacts to NuGet.


- Enable C client GitHub Actions CI:
   - Added a `C/VERSION` file to record the current version of C client
   - Updated `C/build.sh` to be able to run in both local and CI env. Added function to produce a `*.tar.gz` archive.
   - Use `actions/create-release@v1` and `actions/upload-release-asset@v1` to create a release based on new tag and if the version defined in `C/VERSION` does not end with `-SNAPSHOT`.

**Comment by vietj** [comment]
looks great @gaol who is currently managing those tokens ?

can you update the Java CI to use the new distribution infrastructure ? (you can have a look at what changed in other java builds of this organization).

**Comment by gaol** [comment]
> who is currently managing those tokens ?

@vietj  I don't know if the tokens were created or not, and I don't know who is managing the tokens :)

> can you update the Java CI to use the new distribution infrastructure ?

It was up via PR: https://github.com/vert-x3/vertx-eventbus-bridge-clients/pull/41

**Comment by vietj** [comment]
if we were to use the build for releasing, how does it work with respect to
versionning ?

it is not clear

**Comment by gaol** [comment]
> if we were to use the build for releasing, how does it work with respect to versioning ?

In this proposed change, each client has independent version. The clients will be released to different package management system according to the language, each client should keep it's version continuous IMO.

The release process will be triggered with both conditions matched:
- new tag was pushed
- the version string defined in that client indicates that it is a release.(version does not contain `dev`, version does not end with '-SNAPSHOT')

The cons of this proposal:
- it makes it bad mapping between repository tags and client versions
- each client tag push will trigger other client's CI
- maintainer should be careful to keep only one version as releasable on each tag

If each client has it's own repository, that won't be problem, but may need wider discussion.

**Comment by gaol** [comment]
After discussion in discord, we agreed to leave release process manually, so the added CI focus on validation.

@vietj would you please review? thanks :)

**Comment by vietj** [comment]
This is great @gaol thanks, I'll merge it right away.

**Pull request merged**
