### PR TITLE
Improve Python tests

### PR DESCRIPTION
**Pull request by gaol**
Motivation: Improve Python tests following up #47

This PR tries to:
* Add test utils to start a pre-defined eventbus bridge for testing
* Add `test/systemtesting/test_eventbus.py` for integration tests
* Removed un needed tests code

Explain here the context, and why you're making that change, what is the problem you're trying to solve.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by gaol** [comment]
@punkstarman would you please review ? thanks :)

**Comment by punkstarman** [comment]
> @punkstarman would you please review ? thanks :)

With pleasure. I hope to have some time for this by the end of the month.

**Comment by gaol** [comment]
@punkstarman would you please review when you get time? thanks :)

**Review by punkstarman — APPROVED** [review]
Approved! Sorry it took me so long.

**Comment by gaol** [comment]
@punkstarman thanks, :)

**Pull request merged**
